name: CI workflow for MAVEN 
on: push
jobs: 
 CICDjob: 
  env: 
    imagename: "MyJavaApp"
  runs-on: ubuntu-latest
  steps: 
   - name: clone the repo on the runner
     uses: actions/checkout@v4
   - name: Setup java and MAVEN
     uses: actions/setup-java@v4
     with: 
      distribution: 'temurin'
      java-version: 17
      cache: 'maven'
   - name: Build with maven
     run: mvn package
   - name: install docker
     uses: actions/setup-docker-action@v4
   - name: login to docker hub
     uses: docker/login-action@v3
     with: 
       username: ${{secrets.DOCKERHUB_USERNAME}}
       passeord: ${{secrets.DOCKERHUB_PASSWORD}}
   - name: build and push
     uses: docker/build-push-action@v6
     with:
      context: .
      push: true
      tages: ${{secrets.DOCKERHUB_USERNAME}}/${{env.imagename}}:latest
   - name: deploy the image
     run: |
      docker run -d -P ${{secrets.DOCKERHUB_USERNAME}}/${{env.imagename}}:latest
      docker ps -a 
